


apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-llama-svc
  name: my-llama-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: my-llama
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  loadBalancerSourceRanges:
    - 8.29.230.8/32
    - 16.59.37.201/32
